defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "/var/run/docker.sock:/var/run/docker.sock"
domain = "docker.localhost"
exposedByDefault = false
